name: Integration
on:
  pull_request_target:
    branches: [main]
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - "plugins/**"
      - "tests/integration/**"
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      lab_title: ${{ steps.set-title.outputs.lab_title }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Lab Title
        id: set-title
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            echo "lab_title=cisco_ios_PR${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            git_hash=$(git rev-parse --short HEAD)
            uuid=$(uuidgen | cut -c 1-8)
            echo "lab_title=cisco_ios_${git_hash}_${uuid}" >> $GITHUB_OUTPUT
          fi

  integration:
    needs: setup
    uses: ansible/ansible-content-actions/.github/workflows/network_integration.yaml@main
    with:
      lab_title: ${{ needs.setup.outputs.lab_title }}
      network_os: cisco.ios.ios
      pytest_addopts: "--color=yes -n 2 --log-level WARNING -vvv"
      collection_pre_install: >-
        git+https://github.com/ansible-collections/ansible.utils.git
        git+https://github.com/ansible-collections/ansible.netcommon.git
      cml_lab: tests/integration/labs/single.yaml
      integration_test_path: tests/integration/targets
    secrets:
      cml_ssh_password: ${{ secrets.CML_SSH_PASSWORD }}
      virl_host: ${{ secrets.VIRL_HOST }}
      virl_password: ${{ secrets.VIRL_PASSWORD }}
