name: Integration
on:
  pull_request_target:
    branches: [main]
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - "plugins/**"
      - "tests/integration/**"
  workflow_dispatch:

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # After proper checkout, proceed with the reusable workflow
      - name: Run Integration Tests
        uses: ansible/ansible-content-actions/.github/workflows/network_integration.yaml@main
        with:
          lab_title: cisco_ios
          network_os: cisco.ios.ios
          pytest_addopts: "--color=yes -n 2 --log-level WARNING -vvv"
          collection_pre_install: >-
            git+https://github.com/ansible-collections/ansible.utils.git
            git+https://github.com/ansible-collections/ansible.netcommon.git
          cml_lab: tests/integration/labs/single.yaml
          integration_test_path: tests/integration/targets
        secrets:
          cml_ssh_password: ${{ secrets.CML_SSH_PASSWORD }}
          virl_host: ${{ secrets.VIRL_HOST }}
          virl_password: ${{ secrets.VIRL_PASSWORD }}
# ---
# name: Integration
# on:
#   pull_request_target:
#     branches: [main]
#     types:
#       - labeled
#       - opened
#       - reopened
#       - synchronize
#     paths:
#       - "plugins/**"
#       - "tests/integration/**"
#   workflow_dispatch:

# jobs:
#   integration:
#     uses: ansible/ansible-content-actions/.github/workflows/network_integration.yaml@main
#     with:
#       lab_title: cisco_ios
#       network_os: cisco.ios.ios
#       pytest_addopts: "--color=yes -n 2 --log-level WARNING -vvv"
#       collection_pre_install: >-
#         git+https://github.com/ansible-collections/ansible.utils.git
#         git+https://github.com/ansible-collections/ansible.netcommon.git
#     secrets:
#       cml_ssh_password: ${{ secrets.CML_SSH_PASSWORD }}
#       virl_host: ${{ secrets.VIRL_HOST }}
#       virl_password: ${{ secrets.VIRL_PASSWORD }}
