---
name: Integration
on:
  pull_request_target:
    branches: [main]
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - "plugins/**"
      - "tests/integration/**"
  workflow_dispatch:

jobs:
  integration:
    uses: ansible/ansible-content-actions/.github/workflows/network_integration.yaml@main
    with:
      lab_title: cisco_ios_test  # Simple static name for now
      network_os: cisco.ios.ios
      # Modified pytest options to ensure proper test discovery and execution
      pytest_addopts: >-
        --integration-tests-path tests/integration/targets
        --cml-lab tests/integration/labs/single.yaml
        -n 2
        --log-level DEBUG
        -vvv
      # Added required collections
      collection_pre_install: >-
        git+https://github.com/ansible-collections/ansible.utils.git
        git+https://github.com/ansible-collections/ansible.netcommon.git
        git+https://github.com/ansible-collections/cisco.ios.git
    secrets:
      cml_ssh_password: ${{ secrets.CML_SSH_PASSWORD }}
      virl_host: ${{ secrets.VIRL_HOST }}
      virl_password: ${{ secrets.VIRL_PASSWORD }}
